
-- Create site_content table for i18n UI strings
CREATE TABLE public.site_content (
  id integer NOT NULL PRIMARY KEY,
  lang integer NOT NULL DEFAULT 1,
  subheader varchar(100) NOT NULL DEFAULT '',
  description varchar(100) NOT NULL DEFAULT '',
  boardheader varchar(100) NOT NULL DEFAULT '',
  boardtitle varchar(100) NOT NULL DEFAULT '',
  support varchar(100) NOT NULL DEFAULT '',
  passport varchar(100) NOT NULL DEFAULT '',
  website varchar(100) NOT NULL DEFAULT '',
  aboutheader varchar(100) NOT NULL DEFAULT '',
  abouttitle varchar(100) NOT NULL DEFAULT '',
  showmore varchar(100) NOT NULL DEFAULT '',
  addextra varchar(100) NOT NULL DEFAULT '',
  giveus varchar(100) NOT NULL DEFAULT '',
  currency varchar(100) NOT NULL DEFAULT '',
  formheader varchar(100) NOT NULL DEFAULT '',
  formdesc varchar(200) NOT NULL DEFAULT '',
  reaction varchar(100) NOT NULL DEFAULT '',
  formname varchar(100) NOT NULL DEFAULT '',
  formemail varchar(100) NOT NULL DEFAULT '',
  formconfirmemail varchar(100) NOT NULL DEFAULT '',
  formmobile varchar(100) NOT NULL DEFAULT '',
  formterm varchar(100) NOT NULL DEFAULT '',
  formtnc varchar(500) NOT NULL DEFAULT '',
  formmarketing varchar(500) NOT NULL DEFAULT '',
  failedtitle varchar(100) NOT NULL DEFAULT '',
  faileddesc varchar(100) NOT NULL DEFAULT '',
  successtitle varchar(100) NOT NULL DEFAULT '',
  sucessdesc varchar(100) NOT NULL DEFAULT '',
  impactheader varchar(100) NOT NULL DEFAULT '',
  impacttitle varchar(100) NOT NULL DEFAULT '',
  loginemail varchar(100) NOT NULL DEFAULT '',
  loginmobile varchar(100) NOT NULL DEFAULT '',
  getstarted varchar(100) NOT NULL DEFAULT '',
  otpheader varchar(100) NOT NULL DEFAULT '',
  otpdescsms varchar(200) NOT NULL DEFAULT '',
  otpdescemail varchar(500) NOT NULL DEFAULT '',
  verifyotp varchar(100) NOT NULL DEFAULT '',
  resendotp varchar(100) NOT NULL DEFAULT '',
  tryother varchar(100) NOT NULL DEFAULT '',
  needhelp varchar(100) NOT NULL DEFAULT '',
  mypassport varchar(100) NOT NULL DEFAULT '',
  badge varchar(100) NOT NULL DEFAULT '',
  event varchar(100) NOT NULL DEFAULT '',
  impact varchar(100) NOT NULL DEFAULT '',
  travelambassador varchar(100) NOT NULL DEFAULT '',
  impactrecord varchar(100) NOT NULL DEFAULT '',
  summary varchar(100) NOT NULL DEFAULT '',
  detail varchar(100) NOT NULL DEFAULT '',
  sdg varchar(100) NOT NULL DEFAULT '',
  submit varchar(50) NOT NULL DEFAULT '',
  nameerror varchar(100) NOT NULL DEFAULT '',
  mobileerror varchar(100) NOT NULL DEFAULT '',
  termerror varchar(100) NOT NULL DEFAULT '',
  duplicateerror varchar(100) NOT NULL DEFAULT '',
  emailerror varchar(100) NOT NULL DEFAULT '',
  home varchar(50) NOT NULL DEFAULT '',
  invildemail varchar(100) NOT NULL DEFAULT '',
  otpinvalid varchar(100) NOT NULL DEFAULT '',
  otpexpired varchar(100) NOT NULL DEFAULT '',
  contactus varchar(50) NOT NULL DEFAULT '',
  contact varchar(50) NOT NULL DEFAULT '',
  email varchar(50) NOT NULL DEFAULT '',
  collected varchar(200) NOT NULL DEFAULT '',
  greeting varchar(50) NOT NULL DEFAULT ''
);

-- Enable RLS
ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;

-- Anyone can read site content
CREATE POLICY "Anyone can read site content"
ON public.site_content FOR SELECT
USING (true);

-- Only admins can manage
CREATE POLICY "Admins can manage site content"
ON public.site_content FOR ALL
USING (has_role(auth.uid(), 'admin'::app_role));

-- Create sdg_badges table for badge-SDG relationships
CREATE TABLE public.sdg_badges (
  id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  badge_id integer NOT NULL REFERENCES public.badges(id),
  sdg_id integer NOT NULL
);

ALTER TABLE public.sdg_badges ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read sdg_badges"
ON public.sdg_badges FOR SELECT
USING (true);

CREATE POLICY "Admins can manage sdg_badges"
ON public.sdg_badges FOR ALL
USING (has_role(auth.uid(), 'admin'::app_role));

-- Create rankings table for user reactions
CREATE TABLE public.rankings (
  id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  badge_id integer NOT NULL REFERENCES public.badges(id),
  user_id uuid NOT NULL,
  mark_id integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(badge_id, user_id)
);

ALTER TABLE public.rankings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read rankings"
ON public.rankings FOR SELECT
USING (true);

CREATE POLICY "Authenticated users can insert rankings"
ON public.rankings FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own rankings"
ON public.rankings FOR UPDATE
USING (auth.uid() = user_id);
