// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbfybrxpdippdsettdgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiZnlicnhwZGlwcGRzZXR0ZGd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyNjcxMjMsImV4cCI6MjA4Nzg0MzEyM30.jmvtnn6mInBfuX8T8Tua5Yii3HbGIxChooT69QeVDVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});